# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9eff551985264c7e900b8b0a12e875fdec668d4f944efcaefc3f96d2777e39613d5432f3399450d8edeefb738e90ee584a7369f21d689a3e40b3f56fa0d1506a

test:
  secret_key_base: 855e07d43983aba2a8f1698e57ba931898b25b2f2419e7a2c65504c9c6542caeff5dbf1135cf8f3f08aad5c138a3acc063bc2b85b6df8b2b89e41bffb0b349c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
